# Generated by Django 3.1.4 on 2020-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20201202_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvstorage',
            name='file_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
