# Generated by Django 3.1.4 on 2020-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_csvstorage_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvstorage',
            name='file_path',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
